# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:  
  name: MyAgent  

variables:
  buildConfiguration: 'Release'

  #Replace these variables to suit your application
  projectName: 'WeatherService'
  websiteName: 'WeatherService'
  appPoolName: 'WeatherService'

stages:
- stage: 'Build'
  displayName: 'Build'
  jobs:
     - job: 
       steps:  
        # - task: DotNetCoreCLI@2
        #   displayName: 'dotnet restore'
        #   inputs:
        #     command: 'restore'
        #     projects: '*.sln'

        - task: DotNetCoreCLI@2
          displayName: Build
          inputs:
            command: 'build'
            projects: '**/*.csproj'
            arguments: --configuration Release

        - task: DotNetCoreCLI@2
          displayName: Test
          inputs:
            command: test
            projects: '**/*.csproj'
            arguments: '--configuration $(BuildConfiguration)'
       
        - task: DotNetCoreCLI@2
          displayName: 'Publish the project - $(buildConfiguration)'
          inputs:
            command: 'publish'
            projects: '**/*.csproj'
            publishWebProjects: false
            arguments: '--no-build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/$(buildConfiguration)'
            zipAfterPublish: true

        - publish: '$(Build.ArtifactStagingDirectory)'
          artifact: drop

- stage: 'Dev'
  displayName: 'Dev'
  dependsOn: 'Build'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
   - deployment: Dev
     displayName: Dev
     environment: 
       name: 'Dev'
      #  resourceType: VirtualMachine
     variables:
     - name: websitePhysicalPath
       value: '%SystemDrive%\inetpub\wwwroot\$(websiteName)'

     strategy:
      runOnce:
        deploy:
          steps:
          - task: IISWebAppManagementOnMachineGroup@0
            inputs:
              IISDeploymentType: 'IISWebsite'
              ActionIISWebsite: 'CreateOrUpdateWebsite'
              WebsiteName: '$(websiteName)'
              WebsitePhysicalPath: '$(websitePhysicalPath)'
              WebsitePhysicalPathAuth: 'WebsiteUserPassThrough'
              CreateOrUpdateAppPoolForWebsite: true
              AppPoolNameForWebsite: '$(appPoolName)'
              DotNetVersionForWebsite: 'No Managed Code'
              PipeLineModeForWebsite: 'Integrated'
              AppPoolIdentityForWebsite: 'ApplicationPoolIdentity'
              AddBinding: true
              Bindings: |
                  {
                      bindings:[
                          {
                              "protocol":"http",
                              "ipAddress":"",
                              "hostname":"",
                              "port":"8081",
                              "sslThumbprint":"",
                              "sniFlag":false
                          }
                      ]
                  }
          - task: IISWebAppDeploymentOnMachineGroup@0
            inputs:
              WebSiteName: '$(websiteName)'
              Package: '$(System.DefaultWorkingDirectory)\**\*.zip'

          # - task: IISWebAppDeploymentOnMachineGroup@0
          #   inputs:
          #     WebSiteName: '$(websiteName)'
          #     Package: '$(Pipeline.Workspace)/drop/$(buildConfiguration)/$(projectName).zip'
# steps:

# - task: DotNetCoreCLI@2
#   displayName: Build
#   inputs:
#     command: build
#     projects: '**/*.csproj'


# - task: DotNetCoreCLI@2
#   inputs:
#     command: 'pack'
#     packagesToPack: '**/*.csproj'
#     versioningScheme: 'off'
    
# - task: DotNetCoreCLI@2
#   inputs:
#     command: 'publish'
#     publishWebProjects: true

# # - task: IISWebAppDeploymentOnMachineGroup@0
# #   inputs:
# #     WebSiteName: 'IIS_web_app_deploy'
# #     VirtualApplication: 'IIS_web_app_deploy'
# #     Package: '$(System.DefaultWorkingDirectory)\**\*.zip'

# - task: IISWebAppManagementOnMachineGroup@0
#   inputs:
#     EnableIIS: true    
#     IISDeploymentType: 'IISWebsite'
#     ActionIISWebsite: 'CreateOrUpdateWebsite'
#     WebsiteName: 'TestingWeb'
#     WebsitePhysicalPath: '%SystemDrive%\inetpub\wwwroot'
#     WebsitePhysicalPathAuth: 'WebsiteUserPassThrough'
#     CreateOrUpdateAppPoolForWebsite: true
#     AppPoolNameForWebsite: 'TestingWeb'
#     DotNetVersionForWebsite: 'v4.0'
#     PipeLineModeForWebsite: 'Integrated'
#     AppPoolIdentityForWebsite: 'ApplicationPoolIdentity'


