# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:  
  name: MyAgent  

variables:
  buildConfiguration: 'Release'

  #Replace these variables to suit your application
  projectName: 'WeatherService'
  websiteName: 'WeatherService'
  appPoolName: 'WeatherService'

stages:
- stage: 'Build'
  displayName: 'Build'
  jobs:
     - job: 
       steps:  
        # - task: DotNetCoreCLI@2
        #   displayName: 'dotnet restore'
        #   inputs:
        #     command: 'restore'
        #     projects: '*.sln'

        - task: DotNetCoreCLI@2
          displayName: Build
          inputs:
            command: 'build'
            projects: '*.sln'
            arguments: --configuration Release

        - task: DotNetCoreCLI@2
          displayName: Test
          inputs:
            command: test
            projects: '*.sln'
            arguments: '--configuration $(BuildConfiguration)'
       
        - task: DotNetCoreCLI@2
          displayName: 'Publish the project - $(buildConfiguration)'
          inputs:
            command: 'publish'
            projects: '**/*.csproj'
            publishWebProjects: false
            arguments: '--no-build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/$(buildConfiguration)'
            zipAfterPublish: true

        - publish: '$(Build.ArtifactStagingDirectory)'
          artifact: drop
          
# steps:

# - task: DotNetCoreCLI@2
#   displayName: Build
#   inputs:
#     command: build
#     projects: '**/*.csproj'


# - task: DotNetCoreCLI@2
#   inputs:
#     command: 'pack'
#     packagesToPack: '**/*.csproj'
#     versioningScheme: 'off'
    
# - task: DotNetCoreCLI@2
#   inputs:
#     command: 'publish'
#     publishWebProjects: true

# # - task: IISWebAppDeploymentOnMachineGroup@0
# #   inputs:
# #     WebSiteName: 'IIS_web_app_deploy'
# #     VirtualApplication: 'IIS_web_app_deploy'
# #     Package: '$(System.DefaultWorkingDirectory)\**\*.zip'

# - task: IISWebAppManagementOnMachineGroup@0
#   inputs:
#     EnableIIS: true    
#     IISDeploymentType: 'IISWebsite'
#     ActionIISWebsite: 'CreateOrUpdateWebsite'
#     WebsiteName: 'TestingWeb'
#     WebsitePhysicalPath: '%SystemDrive%\inetpub\wwwroot'
#     WebsitePhysicalPathAuth: 'WebsiteUserPassThrough'
#     CreateOrUpdateAppPoolForWebsite: true
#     AppPoolNameForWebsite: 'TestingWeb'
#     DotNetVersionForWebsite: 'v4.0'
#     PipeLineModeForWebsite: 'Integrated'
#     AppPoolIdentityForWebsite: 'ApplicationPoolIdentity'


